# Generated by Django 4.0.2 on 2022-03-15 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_network', '0003_alter_comments_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.restaurantblogs')),
                ('users', models.ManyToManyField(blank=True, related_name='rated_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
