# Generated by Django 4.0 on 2022-04-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_alter_notification_target_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantblogsimg',
            name='img',
            field=models.CharField(max_length=50),
        ),
    ]
