# Generated by Django 4.0.2 on 2022-03-15 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0003_restaurants_dislikes_restaurants_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='dislikes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
