# Generated by Django 4.0.2 on 2022-03-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurants_dislikes_alter_restaurants_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='likes',
        ),
    ]
