# Generated by Django 4.0.2 on 2022-04-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurantmenus_img_alter_restaurants_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='logo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
