# Generated by Django 4.0.2 on 2022-04-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_restaurants_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='logo',
            field=models.ImageField(default='https://post.healthline.com/wp-content/uploads/2020/09/healthy-eating-ingredients-732x549-thumbnail.jpg', upload_to='restaurant_logo/'),
            preserve_default=False,
        ),
    ]
