# Generated by Django 4.0 on 2022-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_restaurants_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='logo',
            field=models.CharField(max_length=100),
        ),
    ]
