# Generated by Django 4.0.2 on 2022-04-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(default='https://p.kindpng.com/picc/s/33-338711_circle-user-icon-blue-hd-png-download.png', upload_to='avatars/'),
        ),
    ]
