# Generated by Django 4.0.2 on 2022-03-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_restaurants_dislikes_remove_restaurants_likes'),
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='comments',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurants'),
        ),
        migrations.AlterField(
            model_name='following',
            name='follow_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='following',
            name='like_status',
            field=models.BooleanField(default=False),
        ),
    ]
