# Generated by Django 4.0.2 on 2022-03-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
