# Generated by Django 4.0 on 2022-04-20 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraccount_avatar'),
        ('social_network', '0007_alter_following_like_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rated',
            name='users',
        ),
        migrations.AddField(
            model_name='rated',
            name='users',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='rated_users', to='accounts.useraccount'),
            preserve_default=False,
        ),
    ]
